### ISSUE TITLE
PDF 

### ISSUE THREAD

**Issue by Spencerx** [dillonHe/EasyEDA-Documents#16]
Hi please can we share an official PDF of the simulation ebook.
Cheers

**Comment by dillonHe** [comment]
Will think about this.

Thanks.

**Comment by signality** [comment]
As previously discussed, I need to revise it anyway before we do anything
with it.

I might be able to generate a pdf easily from my original html version ....

On 19 June 2015 at 10:29, Dillon He notifications@github.com wrote:

> Will think about this.
> 
> Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dillonHe/EasyEDA-Documents/issues/16#issuecomment-113445281
> .

## 

Regards,

Andy Fierman

EasyEDA Team.

   http://easyeda.com/

**Comment by Spencerx** [comment]
With an original source html file I can consider it a non issue.

**Comment by dillonHe** [comment]
Check your email.

**Comment by Spencerx** [comment]
Got it there are options to convert the documentation in one batch for the html archive.

I recommend 

htmldoc
Princexml http://www.princexml.com/download/

I'll get to that as soon as I can and I consider the issue closed.

**Comment by signality** [comment]
You can convert html to pdf using the Free Open Source Software, LibreOffice
http://www.libreoffice.org/.

Open with in LibreOffice Writer

File > Export to PDF

On 20 June 2015 at 12:24, Spencer Tom Tafadzwa Chirume <
notifications@github.com> wrote:

> Got it there are options to convert the documentation in one batch for the
> html archive.
> 
> I recommend
> 
> htmldoc
> Princexml http://www.princexml.com/download/
> 
> I'll get to that as soon as I can and I consider the issue closed.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dillonHe/EasyEDA-Documents/issues/16#issuecomment-113748200
> .

## 

Regards,

Andy Fierman

EasyEDA Team.

   http://easyeda.com/
